// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCghQ7LR1Plvq9FEwWslTgf38yEO1cpfU',
    appId: '1:447611313649:android:5b48ef85f59de9de0a3850',
    messagingSenderId: '447611313649',
    projectId: 'damonn',
    databaseURL: 'https://damonn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'damonn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtE6YtXVUx0cho82oQOCKnlf5O7Xaz9ek',
    appId: '1:447611313649:ios:febabdb8d9517c350a3850',
    messagingSenderId: '447611313649',
    projectId: 'damonn',
    databaseURL: 'https://damonn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'damonn.appspot.com',
    iosClientId: '447611313649-d9e0vufquro0vj40k4rtg858uv2j0nj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.damonn',
  );
}
